services:
  cups2mqtt:
    build:
      context: .
      target: final
    environment:
      C2M_MQTT_HOST: localhost
      C2M_MQTT_PORT: 631
      C2M_MQTT_SECURE: true
      C2M_MQTT_IGNORETLSERRORS: false
      C2M_MQTT_USERNAME:
      C2M_MQTT_PASSWORD:
      C2M_MQTT_CLIENTID: cups2mqtt
      C2M_MQTT_ROOTTOPIC: cups2mqtt

      C2M_MQTT_HA_ENABLEDISCOVERY: false
      C2M_MQTT_HA_DISCOVERYTOPICPREFIX: homeassistant
      C2M_MQTT_HA_COMPONENTID: cups2mqtt

      C2M_CUPS_URI: https://localhost:631/
      C2M_CUPS_IGNORETLSERRORS: true
      C2M_CUPS_USERNAME:
      C2M_CUPS_PASSWORD:

      C2M_SENTRYDSN:
