name: Release - Linux AppImage x86_64

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

# Sets permissions to allow version tag
permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Extract version from branch name
    - name: Extract Release version
      id: extract_release_version
      shell: bash
      run: |
        release_version=$(echo ${{ github.event.pull_request.head.ref }} | cut -d/ -f2)
        echo "release_version=$release_version" >> $GITHUB_OUTPUT

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: |
          h3x4d3c1m4l/cups2mqtt
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=semver,pattern={{major}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=raw,value=latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}

  build-arm64:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}

    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Extract version from branch name
    - name: Extract Release version
      id: extract_release_version
      shell: bash
      run: |
        release_version=$(echo ${{ github.event.pull_request.head.ref }} | cut -d/ -f2)
        echo "release_version=$release_version" >> $GITHUB_OUTPUT

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: |
          h3x4d3c1m4l/cups2mqtt
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=semver,pattern={{major}},value=${{ steps.extract_release_version.outputs.release_version }}
          type=raw,value=latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
